### ISSUE TITLE
Add feature category feature=user_favorites

### ISSUE THREAD

**Issue by Ravennoir** [pla1/plugin.image.500px#3]
It would be a great enhancement to be able to search for users favorites.

Things to do would be to add feature=user_favorites and username=username option.

Thank you for considering.

**Comment by pla1** [comment]
This would require implementing authentication via the OAuth dance. I'll see what I can do. Thanks.

**Comment by snorrelo** [comment]
'user_favorites' is not available anymore. https://github.com/500px/api-documentation/commit/0e7dee22ae2da382a31c41ce3f2564bb8b4a6047

500px now has Galleries APIs, but these are not implemented in python-500px at the moment.

**Comment by pla1** [comment]
@snorrelo Excellent. Pull request submitted to Kodi Addons mailing list. Thanks. ☮
