### ISSUE TITLE
Plugin Broken on Raspberry PI

### ISSUE THREAD

**Issue by Dschubba** [pla1/plugin.image.500px#4]
Currently the Plugin seems to be broken on Raspberry PI at the moment. 

It only shows the list of Pictures, also the preview, but not the picture itself, after pressing the return key.

It also doesn't work with the plugin-slideshow.

**Comment by pla1** [comment]
If you haven't already, try using the Slideshow menu item from the navigation menu on the left (Confluence theme) as seen in this screenshot. Let me know if that works. ![screenshot] (http://i.imgur.com/rOC6t1I.png).

**Comment by Dschubba** [comment]
Hi,

yes - this option works. I've tried the plugin also under Mac OS X/Kodi 14.1 where the same bug exists, also here works the "Slideshow"-Option.

Hope this helps! If I can test anything please let me know!

**Comment by pla1** [comment]
I'm leaning towards this being a Kodi platform bug but I will build a test addon to make sure before I file a bug. Thanks.
