### ISSUE TITLE
Watermarks in photos

### ISSUE THREAD

**Issue by MacLeodMike** [pla1/plugin.image.500px#5]
Looks like 500px changed the API to return watermarked photos now. See this issue: https://github.com/500px/api-documentation/issues/128 which points to https://github.com/500px/api-documentation/blob/master/basics/formats_and_terms.md#image-urls-and-image-sizes

Any chance it can be arranged to have the watermark removed for this app? It's really distracting and for the time being I've changed to using the flickr plugin, but 500px has better images generally.

**Comment by pla1** [comment]
I sent an email sales@500px.com asking to provide images without watermarks. I'll let you know if I hear from them.

**Comment by pla1** [comment]
This is the response from 500px ![response from 500px] (http://i.imgur.com/PPzmRTd.png).
