### ISSUE TITLE
Content type assignment

### ISSUE THREAD

**Issue by phil65** [pla1/plugin.image.500px#7]
It would be nice if you could set content type to "images" in case the list contains pictures. 
See http://forum.kodi.tv/showthread.php?tid=250936&pid=2246088#pid2246088
Thx!

**Comment by phil65** [comment]
?

**Comment by pla1** [comment]
@phil65 

Sorry about prematurely closing this issue. Is this what you are requesting? 

`xbmcplugin.setContent(addon_handle, 'images')`

Thanks, PLA

**Comment by phil65** [comment]
correct, but only in cases where the list really contains images, and not some directory nodes.

**Comment by pla1** [comment]
Done. https://github.com/pla1/plugin.image.500px/commit/50efe039edfc6114b60ecf4d0f1500cd8027d7ce#diff-e87f4dd869f897586689ccfd0fa643d5
